/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.table.record;

import net.feminaexlux.player.model.table.MoodResource;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MoodResourceRecord extends UpdatableRecordImpl<MoodResourceRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = 1177617660;

	/**
	 * Setter for <code>media.mood_resource.mood</code>.
	 */
	public void setMood(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.mood_resource.mood</code>.
	 */
	public String getMood() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>media.mood_resource.user</code>.
	 */
	public void setUser(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.mood_resource.user</code>.
	 */
	public String getUser() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>media.mood_resource.resource</code>.
	 */
	public void setResource(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.mood_resource.resource</code>.
	 */
	public String getResource() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return MoodResource.MOOD_RESOURCE.MOOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return MoodResource.MOOD_RESOURCE.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return MoodResource.MOOD_RESOURCE.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getMood();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord value1(String value) {
		setMood(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord value2(String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord value3(String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord values(String value1, String value2, String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MoodResourceRecord
	 */
	public MoodResourceRecord() {
		super(MoodResource.MOOD_RESOURCE);
	}

	/**
	 * Create a detached, initialised MoodResourceRecord
	 */
	public MoodResourceRecord(String mood, String user, String resource) {
		super(MoodResource.MOOD_RESOURCE);

		setValue(0, mood);
		setValue(1, user);
		setValue(2, resource);
	}
}
