/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.table.record;

import net.feminaexlux.player.model.table.Resource;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ResourceRecord extends UpdatableRecordImpl<ResourceRecord> implements Record5<String, String, String, String, Timestamp> {

	private static final long serialVersionUID = 859670900;

	/**
	 * Setter for <code>media.resource.checksum</code>.
	 */
	public void setChecksum(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.resource.checksum</code>.
	 */
	public String getChecksum() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>media.resource.directory</code>.
	 */
	public void setDirectory(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.resource.directory</code>.
	 */
	public String getDirectory() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>media.resource.type</code>.
	 */
	public void setType(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.resource.type</code>.
	 */
	public String getType() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>media.resource.path</code>.
	 */
	public void setPath(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>media.resource.path</code>.
	 */
	public String getPath() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>media.resource.last_updated</code>.
	 */
	public void setLastUpdated(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>media.resource.last_updated</code>.
	 */
	public Timestamp getLastUpdated() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Resource.RESOURCE.CHECKSUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Resource.RESOURCE.DIRECTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Resource.RESOURCE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Resource.RESOURCE.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Resource.RESOURCE.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getChecksum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDirectory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value1(String value) {
		setChecksum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value2(String value) {
		setDirectory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value3(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value4(String value) {
		setPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value5(Timestamp value) {
		setLastUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord values(String value1, String value2, String value3, String value4, Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResourceRecord
	 */
	public ResourceRecord() {
		super(Resource.RESOURCE);
	}

	/**
	 * Create a detached, initialised ResourceRecord
	 */
	public ResourceRecord(String checksum, String directory, String type, String path, Timestamp lastUpdated) {
		super(Resource.RESOURCE);

		setValue(0, checksum);
		setValue(1, directory);
		setValue(2, type);
		setValue(3, path);
		setValue(4, lastUpdated);
	}
}
