/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

import net.feminaexlux.player.model.Keys;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.tables.records.MoodResourceRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MoodResource extends TableImpl<MoodResourceRecord> {

	private static final long serialVersionUID = -1245456600;

	/**
	 * The reference instance of <code>media.mood_resource</code>
	 */
	public static final MoodResource MOOD_RESOURCE = new MoodResource();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MoodResourceRecord> getRecordType() {
		return MoodResourceRecord.class;
	}

	/**
	 * The column <code>media.mood_resource.mood</code>.
	 */
	public final TableField<MoodResourceRecord, String> MOOD = createField("mood", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.mood_resource.resource</code>.
	 */
	public final TableField<MoodResourceRecord, String> RESOURCE = createField("resource", SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * Create a <code>media.mood_resource</code> table reference
	 */
	public MoodResource() {
		this("mood_resource", null);
	}

	/**
	 * Create an aliased <code>media.mood_resource</code> table reference
	 */
	public MoodResource(String alias) {
		this(alias, MoodResource.MOOD_RESOURCE);
	}

	private MoodResource(String alias, Table<MoodResourceRecord> aliased) {
		this(alias, aliased, null);
	}

	private MoodResource(String alias, Table<MoodResourceRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MoodResourceRecord> getPrimaryKey() {
		return Keys.KEY_MOOD_RESOURCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MoodResourceRecord>> getKeys() {
		return Arrays.<UniqueKey<MoodResourceRecord>>asList(Keys.KEY_MOOD_RESOURCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<org.jooq.ForeignKey<MoodResourceRecord, ?>> getReferences() {
		return Arrays.<org.jooq.ForeignKey<MoodResourceRecord, ?>>asList(Keys.FK1_MOOD_RESOURCE_MOOD, Keys.FK2_MOOD_RESOURCE_RESOURCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResource as(String alias) {
		return new MoodResource(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MoodResource rename(String name) {
		return new MoodResource(name, null);
	}
}
