/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NormalizedText extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.NormalizedTextRecord> {

	private static final long serialVersionUID = -551332260;

	/**
	 * The reference instance of <code>media.normalized_text</code>
	 */
	public static final net.feminaexlux.player.model.tables.NormalizedText NORMALIZED_TEXT = new net.feminaexlux.player.model.tables.NormalizedText();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.NormalizedTextRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.NormalizedTextRecord.class;
	}

	/**
	 * The column <code>media.normalized_text.original</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.NormalizedTextRecord, java.lang.String> ORIGINAL = createField("original", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.normalized_text.normalized</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.NormalizedTextRecord, java.lang.String> NORMALIZED = createField("normalized", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.normalized_text</code> table reference
	 */
	public NormalizedText() {
		this("normalized_text", null);
	}

	/**
	 * Create an aliased <code>media.normalized_text</code> table reference
	 */
	public NormalizedText(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.NormalizedText.NORMALIZED_TEXT);
	}

	private NormalizedText(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.NormalizedTextRecord> aliased) {
		this(alias, aliased, null);
	}

	private NormalizedText(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.NormalizedTextRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.NormalizedTextRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_NORMALIZED_TEXT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.NormalizedTextRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.NormalizedTextRecord>>asList(net.feminaexlux.player.model.Keys.KEY_NORMALIZED_TEXT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.NormalizedText as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.NormalizedText(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.NormalizedText rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.NormalizedText(name, null);
	}
}
