/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaylistEntry extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> {

	private static final long serialVersionUID = 1399704902;

	/**
	 * The reference instance of <code>media.playlist_entry</code>
	 */
	public static final net.feminaexlux.player.model.tables.PlaylistEntry PLAYLIST_ENTRY = new net.feminaexlux.player.model.tables.PlaylistEntry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.PlaylistEntryRecord.class;
	}

	/**
	 * The column <code>media.playlist_entry.playlist</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord, java.lang.String> PLAYLIST = createField("playlist", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.playlist_entry.order</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord, java.lang.Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>media.playlist_entry.resource</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord, java.lang.String> RESOURCE = createField("resource", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * Create a <code>media.playlist_entry</code> table reference
	 */
	public PlaylistEntry() {
		this("playlist_entry", null);
	}

	/**
	 * Create an aliased <code>media.playlist_entry</code> table reference
	 */
	public PlaylistEntry(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY);
	}

	private PlaylistEntry(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> aliased) {
		this(alias, aliased, null);
	}

	private PlaylistEntry(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_PLAYLIST_ENTRY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord>>asList(net.feminaexlux.player.model.Keys.KEY_PLAYLIST_ENTRY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord, ?>>asList(net.feminaexlux.player.model.Keys.FK1_PLAYLIST_ENTRY_PLAYLIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.PlaylistEntry as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.PlaylistEntry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.PlaylistEntry rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.PlaylistEntry(name, null);
	}
}
