/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

import net.feminaexlux.player.model.Keys;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.tables.records.PlaylistRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Playlist extends TableImpl<PlaylistRecord> {

	private static final long serialVersionUID = -1912426632;

	/**
	 * The reference instance of <code>media.playlist</code>
	 */
	public static final Playlist PLAYLIST = new Playlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlaylistRecord> getRecordType() {
		return PlaylistRecord.class;
	}

	/**
	 * The column <code>media.playlist.name</code>.
	 */
	public final TableField<PlaylistRecord, String> NAME = createField("name", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.playlist</code> table reference
	 */
	public Playlist() {
		this("playlist", null);
	}

	/**
	 * Create an aliased <code>media.playlist</code> table reference
	 */
	public Playlist(String alias) {
		this(alias, Playlist.PLAYLIST);
	}

	private Playlist(String alias, Table<PlaylistRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playlist(String alias, Table<PlaylistRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PlaylistRecord> getPrimaryKey() {
		return Keys.KEY_PLAYLIST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PlaylistRecord>> getKeys() {
		return Arrays.<UniqueKey<PlaylistRecord>>asList(Keys.KEY_PLAYLIST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Playlist as(String alias) {
		return new Playlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Playlist rename(String name) {
		return new Playlist(name, null);
	}
}
