/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Playlist extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.PlaylistRecord> {

	private static final long serialVersionUID = -1912426632;

	/**
	 * The reference instance of <code>media.playlist</code>
	 */
	public static final net.feminaexlux.player.model.tables.Playlist PLAYLIST = new net.feminaexlux.player.model.tables.Playlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.PlaylistRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.PlaylistRecord.class;
	}

	/**
	 * The column <code>media.playlist.name</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.PlaylistRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.playlist</code> table reference
	 */
	public Playlist() {
		this("playlist", null);
	}

	/**
	 * Create an aliased <code>media.playlist</code> table reference
	 */
	public Playlist(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.Playlist.PLAYLIST);
	}

	private Playlist(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.PlaylistRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playlist(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.PlaylistRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_PLAYLIST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.PlaylistRecord>>asList(net.feminaexlux.player.model.Keys.KEY_PLAYLIST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.Playlist as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.Playlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.Playlist rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.Playlist(name, null);
	}
}
