/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

import net.feminaexlux.player.model.Keys;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.tables.records.PrincipleRoleRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PrincipleRole extends TableImpl<PrincipleRoleRecord> {

	private static final long serialVersionUID = 928240853;

	/**
	 * The reference instance of <code>media.principle_role</code>
	 */
	public static final PrincipleRole PRINCIPLE_ROLE = new PrincipleRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrincipleRoleRecord> getRecordType() {
		return PrincipleRoleRecord.class;
	}

	/**
	 * The column <code>media.principle_role.username</code>.
	 */
	public final TableField<PrincipleRoleRecord, String> USERNAME = createField("username", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principle_role.role</code>.
	 */
	public final TableField<PrincipleRoleRecord, String> ROLE = createField("role", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.principle_role</code> table reference
	 */
	public PrincipleRole() {
		this("principle_role", null);
	}

	/**
	 * Create an aliased <code>media.principle_role</code> table reference
	 */
	public PrincipleRole(String alias) {
		this(alias, PrincipleRole.PRINCIPLE_ROLE);
	}

	private PrincipleRole(String alias, Table<PrincipleRoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private PrincipleRole(String alias, Table<PrincipleRoleRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrincipleRoleRecord> getPrimaryKey() {
		return Keys.KEY_PRINCIPLE_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrincipleRoleRecord>> getKeys() {
		return Arrays.<UniqueKey<PrincipleRoleRecord>>asList(Keys.KEY_PRINCIPLE_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PrincipleRoleRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PrincipleRoleRecord, ?>>asList(Keys.FK1_PRINCIPLE_ROLE_PRINCIPLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrincipleRole as(String alias) {
		return new PrincipleRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PrincipleRole rename(String name) {
		return new PrincipleRole(name, null);
	}
}
