/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

import net.feminaexlux.player.model.Keys;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.tables.records.PrincipalRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Principal extends TableImpl<PrincipalRecord> {

	private static final long serialVersionUID = -1094079425;

	/**
	 * The reference instance of <code>media.principle</code>
	 */
	public static final Principal PRINCIPAL = new Principal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrincipalRecord> getRecordType() {
		return PrincipalRecord.class;
	}

	/**
	 * The column <code>media.principle.username</code>.
	 */
	public final TableField<PrincipalRecord, String> USERNAME = createField("username", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principle.password</code>.
	 */
	public final TableField<PrincipalRecord, String> PASSWORD = createField("password", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principle.name</code>.
	 */
	public final TableField<PrincipalRecord, String> NAME = createField("name", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principle.lastLogin</code>.
	 */
	public final TableField<PrincipalRecord, Timestamp> LASTLOGIN = createField("lastLogin", SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>media.principle</code> table reference
	 */
	public Principal() {
		this("principal", null);
	}

	/**
	 * Create an aliased <code>media.principle</code> table reference
	 */
	public Principal(String alias) {
		this(alias, Principal.PRINCIPAL);
	}

	private Principal(String alias, Table<PrincipalRecord> aliased) {
		this(alias, aliased, null);
	}

	private Principal(String alias, Table<PrincipalRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrincipalRecord> getPrimaryKey() {
		return Keys.KEY_PRINCIPAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrincipalRecord>> getKeys() {
		return Arrays.<UniqueKey<PrincipalRecord>>asList(Keys.KEY_PRINCIPAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Principal as(String alias) {
		return new Principal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Principal rename(String name) {
		return new Principal(name, null);
	}
}
