/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

import net.feminaexlux.player.model.Keys;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.tables.records.PrincipalRoleRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PrincipalRole extends TableImpl<PrincipalRoleRecord> {

	private static final long serialVersionUID = 928240853;

	/**
	 * The reference instance of <code>media.principle_role</code>
	 */
	public static final PrincipalRole PRINCIPAL_ROLE = new PrincipalRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrincipalRoleRecord> getRecordType() {
		return PrincipalRoleRecord.class;
	}

	/**
	 * The column <code>media.principle_role.username</code>.
	 */
	public final TableField<PrincipalRoleRecord, String> USERNAME = createField("username", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principle_role.role</code>.
	 */
	public final TableField<PrincipalRoleRecord, String> ROLE = createField("role", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.principle_role</code> table reference
	 */
	public PrincipalRole() {
		this("principal_role", null);
	}

	/**
	 * Create an aliased <code>media.principle_role</code> table reference
	 */
	public PrincipalRole(String alias) {
		this(alias, PrincipalRole.PRINCIPAL_ROLE);
	}

	private PrincipalRole(String alias, Table<PrincipalRoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private PrincipalRole(String alias, Table<PrincipalRoleRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrincipalRoleRecord> getPrimaryKey() {
		return Keys.KEY_PRINCIPAL_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrincipalRoleRecord>> getKeys() {
		return Arrays.<UniqueKey<PrincipalRoleRecord>>asList(Keys.KEY_PRINCIPAL_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PrincipalRoleRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PrincipalRoleRecord, ?>>asList(Keys.FK1_PRINCIPAL_ROLE_PRINCIPAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrincipalRole as(String alias) {
		return new PrincipalRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PrincipalRole rename(String name) {
		return new PrincipalRole(name, null);
	}
}
