/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Resource extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.ResourceRecord> {

	private static final long serialVersionUID = 1803857141;

	/**
	 * The reference instance of <code>media.resource</code>
	 */
	public static final net.feminaexlux.player.model.tables.Resource RESOURCE = new net.feminaexlux.player.model.tables.Resource();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.ResourceRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.ResourceRecord.class;
	}

	/**
	 * The column <code>media.resource.checksum</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.ResourceRecord, java.lang.String> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>media.resource.directory</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.ResourceRecord, java.lang.String> DIRECTORY = createField("directory", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.resource.name</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.ResourceRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.resource.lastAccessed</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.ResourceRecord, java.sql.Timestamp> LASTACCESSED = createField("lastAccessed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>media.resource</code> table reference
	 */
	public Resource() {
		this("resource", null);
	}

	/**
	 * Create an aliased <code>media.resource</code> table reference
	 */
	public Resource(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.Resource.RESOURCE);
	}

	private Resource(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.ResourceRecord> aliased) {
		this(alias, aliased, null);
	}

	private Resource(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.ResourceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.ResourceRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_RESOURCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.ResourceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.ResourceRecord>>asList(net.feminaexlux.player.model.Keys.KEY_RESOURCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.ResourceRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.ResourceRecord, ?>>asList(net.feminaexlux.player.model.Keys.FK1_RESOURCE_DIRECTORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.Resource as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.Resource(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.Resource rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.Resource(name, null);
	}
}
