/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Type extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.TypeRecord> {

	private static final long serialVersionUID = -1981135211;

	/**
	 * The reference instance of <code>media.type</code>
	 */
	public static final net.feminaexlux.player.model.tables.Type TYPE = new net.feminaexlux.player.model.tables.Type();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.TypeRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.TypeRecord.class;
	}

	/**
	 * The column <code>media.type.type</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.TypeRecord, java.lang.String> TYPE_ = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>media.type</code> table reference
	 */
	public Type() {
		this("type", null);
	}

	/**
	 * Create an aliased <code>media.type</code> table reference
	 */
	public Type(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.Type.TYPE);
	}

	private Type(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.TypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Type(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.TypeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeRecord>>asList(net.feminaexlux.player.model.Keys.KEY_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.Type as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.Type(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.Type rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.Type(name, null);
	}
}
