/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TypeExtension extends org.jooq.impl.TableImpl<net.feminaexlux.player.model.tables.records.TypeExtensionRecord> {

	private static final long serialVersionUID = 1562554025;

	/**
	 * The reference instance of <code>media.type_extension</code>
	 */
	public static final net.feminaexlux.player.model.tables.TypeExtension TYPE_EXTENSION = new net.feminaexlux.player.model.tables.TypeExtension();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.feminaexlux.player.model.tables.records.TypeExtensionRecord> getRecordType() {
		return net.feminaexlux.player.model.tables.records.TypeExtensionRecord.class;
	}

	/**
	 * The column <code>media.type_extension.type</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.TypeExtensionRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>media.type_extension.extension</code>.
	 */
	public final org.jooq.TableField<net.feminaexlux.player.model.tables.records.TypeExtensionRecord, java.lang.String> EXTENSION = createField("extension", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>media.type_extension</code> table reference
	 */
	public TypeExtension() {
		this("type_extension", null);
	}

	/**
	 * Create an aliased <code>media.type_extension</code> table reference
	 */
	public TypeExtension(java.lang.String alias) {
		this(alias, net.feminaexlux.player.model.tables.TypeExtension.TYPE_EXTENSION);
	}

	private TypeExtension(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.TypeExtensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private TypeExtension(java.lang.String alias, org.jooq.Table<net.feminaexlux.player.model.tables.records.TypeExtensionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.feminaexlux.player.model.Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeExtensionRecord> getPrimaryKey() {
		return net.feminaexlux.player.model.Keys.KEY_TYPE_EXTENSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeExtensionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.feminaexlux.player.model.tables.records.TypeExtensionRecord>>asList(net.feminaexlux.player.model.Keys.KEY_TYPE_EXTENSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.TypeExtensionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.feminaexlux.player.model.tables.records.TypeExtensionRecord, ?>>asList(net.feminaexlux.player.model.Keys.FK1_TYPE_EXTENSION_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.feminaexlux.player.model.tables.TypeExtension as(java.lang.String alias) {
		return new net.feminaexlux.player.model.tables.TypeExtension(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.feminaexlux.player.model.tables.TypeExtension rename(java.lang.String name) {
		return new net.feminaexlux.player.model.tables.TypeExtension(name, null);
	}
}
