/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.table;

import net.feminaexlux.player.model.Key;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.table.record.PrincipalResourceAccessRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PrincipalResourceAccess extends TableImpl<PrincipalResourceAccessRecord> {

	private static final long serialVersionUID = -2063019406;

	/**
	 * The reference instance of <code>media.principal_resource_access</code>
	 */
	public static final PrincipalResourceAccess PRINCIPAL_RESOURCE_ACCESS = new PrincipalResourceAccess();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrincipalResourceAccessRecord> getRecordType() {
		return PrincipalResourceAccessRecord.class;
	}

	/**
	 * The column <code>media.principal_resource_access.user</code>.
	 */
	public final TableField<PrincipalResourceAccessRecord, String> USER = createField("user", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.principal_resource_access.resource</code>.
	 */
	public final TableField<PrincipalResourceAccessRecord, String> RESOURCE = createField("resource", SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>media.principal_resource_access.lastAccessed</code>.
	 */
	public final TableField<PrincipalResourceAccessRecord, Timestamp> LASTACCESSED = createField("lastAccessed", SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>media.principal_resource_access</code> table reference
	 */
	public PrincipalResourceAccess() {
		this("principal_resource_access", null);
	}

	/**
	 * Create an aliased <code>media.principal_resource_access</code> table reference
	 */
	public PrincipalResourceAccess(String alias) {
		this(alias, PrincipalResourceAccess.PRINCIPAL_RESOURCE_ACCESS);
	}

	private PrincipalResourceAccess(String alias, Table<PrincipalResourceAccessRecord> aliased) {
		this(alias, aliased, null);
	}

	private PrincipalResourceAccess(String alias, Table<PrincipalResourceAccessRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrincipalResourceAccessRecord> getPrimaryKey() {
		return Key.KEY_PRINCIPAL_RESOURCE_ACCESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrincipalResourceAccessRecord>> getKeys() {
		return Arrays.<UniqueKey<PrincipalResourceAccessRecord>>asList(Key.KEY_PRINCIPAL_RESOURCE_ACCESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PrincipalResourceAccessRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PrincipalResourceAccessRecord, ?>>asList(Key.FK1_PRINCIPAL_RESOURCE_ACCESS_PRINCIPAL, Key.FK2_PRINCIPAL_RESOURCE_ACCESS_RESOURCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrincipalResourceAccess as(String alias) {
		return new PrincipalResourceAccess(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PrincipalResourceAccess rename(String name) {
		return new PrincipalResourceAccess(name, null);
	}
}
