/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.table;

import net.feminaexlux.player.model.Key;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.table.record.TypeExtensionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TypeExtension extends TableImpl<TypeExtensionRecord> {

	private static final long serialVersionUID = 680082719;

	/**
	 * The reference instance of <code>media.type_extension</code>
	 */
	public static final TypeExtension TYPE_EXTENSION = new TypeExtension();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TypeExtensionRecord> getRecordType() {
		return TypeExtensionRecord.class;
	}

	/**
	 * The column <code>media.type_extension.type</code>.
	 */
	public final TableField<TypeExtensionRecord, String> TYPE = createField("type", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.type_extension.extension</code>.
	 */
	public final TableField<TypeExtensionRecord, String> EXTENSION = createField("extension", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.type_extension</code> table reference
	 */
	public TypeExtension() {
		this("type_extension", null);
	}

	/**
	 * Create an aliased <code>media.type_extension</code> table reference
	 */
	public TypeExtension(String alias) {
		this(alias, TypeExtension.TYPE_EXTENSION);
	}

	private TypeExtension(String alias, Table<TypeExtensionRecord> aliased) {
		this(alias, aliased, null);
	}

	private TypeExtension(String alias, Table<TypeExtensionRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TypeExtensionRecord> getPrimaryKey() {
		return Key.KEY_TYPE_EXTENSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TypeExtensionRecord>> getKeys() {
		return Arrays.<UniqueKey<TypeExtensionRecord>>asList(Key.KEY_TYPE_EXTENSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TypeExtensionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TypeExtensionRecord, ?>>asList(Key.FK1_TYPE_EXTENSION_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TypeExtension as(String alias) {
		return new TypeExtension(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TypeExtension rename(String name) {
		return new TypeExtension(name, null);
	}
}
