/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.table;

import net.feminaexlux.player.model.Key;
import net.feminaexlux.player.model.Media;
import net.feminaexlux.player.model.table.record.UserRoleRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRole extends TableImpl<UserRoleRecord> {

	private static final long serialVersionUID = 379801037;

	/**
	 * The reference instance of <code>media.user_role</code>
	 */
	public static final UserRole USER_ROLE = new UserRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserRoleRecord> getRecordType() {
		return UserRoleRecord.class;
	}

	/**
	 * The column <code>media.user_role.username</code>.
	 */
	public final TableField<UserRoleRecord, String> USERNAME = createField("username", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>media.user_role.role</code>.
	 */
	public final TableField<UserRoleRecord, String> ROLE = createField("role", SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>media.user_role</code> table reference
	 */
	public UserRole() {
		this("user_role", null);
	}

	/**
	 * Create an aliased <code>media.user_role</code> table reference
	 */
	public UserRole(String alias) {
		this(alias, UserRole.USER_ROLE);
	}

	private UserRole(String alias, Table<UserRoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserRole(String alias, Table<UserRoleRecord> aliased, Field<?>[] parameters) {
		super(alias, Media.MEDIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserRoleRecord> getPrimaryKey() {
		return Key.KEY_USER_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserRoleRecord>> getKeys() {
		return Arrays.<UniqueKey<UserRoleRecord>>asList(Key.KEY_USER_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<UserRoleRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<UserRoleRecord, ?>>asList(Key.FK1_USER_ROLE_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRole as(String alias) {
		return new UserRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserRole rename(String name) {
		return new UserRole(name, null);
	}
}
