/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model;

import net.feminaexlux.player.model.table.Directory;
import net.feminaexlux.player.model.table.Music;
import net.feminaexlux.player.model.table.Resource;
import net.feminaexlux.player.model.table.Type;
import net.feminaexlux.player.model.table.TypeExtension;
import net.feminaexlux.player.model.table.User;
import net.feminaexlux.player.model.table.UserPlayed;
import net.feminaexlux.player.model.table.UserRole;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Media extends SchemaImpl {

	private static final long serialVersionUID = -1851310360;

	/**
	 * The reference instance of <code>media</code>
	 */
	public static final Media MEDIA = new Media();

	/**
	 * No further instances allowed
	 */
	private Media() {
		super("media");
	}

	@Override
	public final List<org.jooq.Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<org.jooq.Table<?>> getTables0() {
		return Arrays.<org.jooq.Table<?>>asList(
				Directory.DIRECTORY,
				Music.MUSIC,
				Resource.RESOURCE,
				Type.TYPE,
				TypeExtension.TYPE_EXTENSION,
				User.USER,
				UserPlayed.USER_PLAYED,
				UserRole.USER_ROLE);
	}
}
