/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model;

import net.feminaexlux.player.model.tables.Directory;
import net.feminaexlux.player.model.tables.Mood;
import net.feminaexlux.player.model.tables.MoodResource;
import net.feminaexlux.player.model.tables.Music;
import net.feminaexlux.player.model.tables.NormalizedText;
import net.feminaexlux.player.model.tables.Playlist;
import net.feminaexlux.player.model.tables.PlaylistEntry;
import net.feminaexlux.player.model.tables.Resource;
import net.feminaexlux.player.model.tables.Type;
import net.feminaexlux.player.model.tables.TypeExtension;

import javax.annotation.Generated;

/**
 * Convenience access to all tables in media
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table media.directory
	 */
	public static final Directory DIRECTORY = Directory.DIRECTORY;

	/**
	 * The table media.mood
	 */
	public static final Mood MOOD = Mood.MOOD;

	/**
	 * The table media.mood_resource
	 */
	public static final MoodResource MOOD_RESOURCE = MoodResource.MOOD_RESOURCE;

	/**
	 * The table media.music
	 */
	public static final Music MUSIC = Music.MUSIC;

	/**
	 * The table media.normalized_text
	 */
	public static final NormalizedText NORMALIZED_TEXT = NormalizedText.NORMALIZED_TEXT;

	/**
	 * The table media.playlist
	 */
	public static final Playlist PLAYLIST = Playlist.PLAYLIST;

	/**
	 * The table media.playlist_entry
	 */
	public static final PlaylistEntry PLAYLIST_ENTRY = PlaylistEntry.PLAYLIST_ENTRY;

	/**
	 * The table media.resource
	 */
	public static final Resource RESOURCE = Resource.RESOURCE;

	/**
	 * The table media.type
	 */
	public static final Type TYPE = Type.TYPE;

	/**
	 * The table media.type_extension
	 */
	public static final TypeExtension TYPE_EXTENSION = TypeExtension.TYPE_EXTENSION;
}
