/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model;

import net.feminaexlux.player.model.table.Directory;
import net.feminaexlux.player.model.table.Music;
import net.feminaexlux.player.model.table.Resource;
import net.feminaexlux.player.model.table.Type;
import net.feminaexlux.player.model.table.TypeExtension;
import net.feminaexlux.player.model.table.User;
import net.feminaexlux.player.model.table.UserPlayed;
import net.feminaexlux.player.model.table.UserRole;

import javax.annotation.Generated;

/**
 * Convenience access to all tables in media
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Table {

	/**
	 * The table media.directory
	 */
	public static final Directory DIRECTORY = Directory.DIRECTORY;

	/**
	 * The table media.music
	 */
	public static final Music MUSIC = Music.MUSIC;

	/**
	 * The table media.resource
	 */
	public static final Resource RESOURCE = Resource.RESOURCE;

	/**
	 * The table media.type
	 */
	public static final Type TYPE = Type.TYPE;

	/**
	 * The table media.type_extension
	 */
	public static final TypeExtension TYPE_EXTENSION = TypeExtension.TYPE_EXTENSION;

	/**
	 * The table media.user
	 */
	public static final User USER = User.USER;

	/**
	 * The table media.user_played
	 */
	public static final UserPlayed USER_PLAYED = UserPlayed.USER_PLAYED;

	/**
	 * The table media.user_role
	 */
	public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
