/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MoodResourceRecord extends org.jooq.impl.UpdatableRecordImpl<net.feminaexlux.player.model.tables.records.MoodResourceRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 425925595;

	/**
	 * Setter for <code>media.mood_resource.mood</code>.
	 */
	public void setMood(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.mood_resource.mood</code>.
	 */
	public java.lang.String getMood() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>media.mood_resource.resource</code>.
	 */
	public void setResource(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.mood_resource.resource</code>.
	 */
	public java.lang.String getResource() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.feminaexlux.player.model.tables.MoodResource.MOOD_RESOURCE.MOOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return net.feminaexlux.player.model.tables.MoodResource.MOOD_RESOURCE.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getMood();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord value1(java.lang.String value) {
		setMood(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord value2(java.lang.String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MoodResourceRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MoodResourceRecord
	 */
	public MoodResourceRecord() {
		super(net.feminaexlux.player.model.tables.MoodResource.MOOD_RESOURCE);
	}

	/**
	 * Create a detached, initialised MoodResourceRecord
	 */
	public MoodResourceRecord(java.lang.String mood, java.lang.String resource) {
		super(net.feminaexlux.player.model.tables.MoodResource.MOOD_RESOURCE);

		setValue(0, mood);
		setValue(1, resource);
	}
}
