/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MusicRecord extends org.jooq.impl.UpdatableRecordImpl<net.feminaexlux.player.model.tables.records.MusicRecord> implements org.jooq.Record7<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = -366299170;

	/**
	 * Setter for <code>media.music.resource</code>.
	 */
	public void setResource(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.music.resource</code>.
	 */
	public java.lang.String getResource() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>media.music.artist</code>.
	 */
	public void setArtist(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.music.artist</code>.
	 */
	public java.lang.String getArtist() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>media.music.album</code>.
	 */
	public void setAlbum(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.music.album</code>.
	 */
	public java.lang.String getAlbum() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>media.music.track</code>.
	 */
	public void setTrack(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>media.music.track</code>.
	 */
	public java.lang.Integer getTrack() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>media.music.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>media.music.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>media.music.genre</code>.
	 */
	public void setGenre(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>media.music.genre</code>.
	 */
	public java.lang.String getGenre() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>media.music.rating</code>.
	 */
	public void setRating(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>media.music.rating</code>.
	 */
	public java.lang.Byte getRating() {
		return (java.lang.Byte) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.ARTIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.GENRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return net.feminaexlux.player.model.tables.Music.MUSIC.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getArtist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAlbum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getTrack();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getGenre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value1(java.lang.String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value2(java.lang.String value) {
		setArtist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value3(java.lang.String value) {
		setAlbum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value4(java.lang.Integer value) {
		setTrack(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value5(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value6(java.lang.String value) {
		setGenre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value7(java.lang.Byte value) {
		setRating(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.String value5, java.lang.String value6, java.lang.Byte value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MusicRecord
	 */
	public MusicRecord() {
		super(net.feminaexlux.player.model.tables.Music.MUSIC);
	}

	/**
	 * Create a detached, initialised MusicRecord
	 */
	public MusicRecord(java.lang.String resource, java.lang.String artist, java.lang.String album, java.lang.Integer track, java.lang.String title, java.lang.String genre, java.lang.Byte rating) {
		super(net.feminaexlux.player.model.tables.Music.MUSIC);

		setValue(0, resource);
		setValue(1, artist);
		setValue(2, album);
		setValue(3, track);
		setValue(4, title);
		setValue(5, genre);
		setValue(6, rating);
	}
}
