/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

import net.feminaexlux.player.model.tables.PlaylistEntry;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaylistEntryRecord extends UpdatableRecordImpl<PlaylistEntryRecord> implements Record4<String, String, Integer, String> {

	private static final long serialVersionUID = 1676566720;

	/**
	 * Setter for <code>media.playlist_entry.playlist</code>.
	 */
	public void setPlaylist(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.playlist</code>.
	 */
	public String getPlaylist() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>media.playlist_entry.user</code>.
	 */
	public void setUser(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.user</code>.
	 */
	public String getUser() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>media.playlist_entry.order</code>.
	 */
	public void setOrder(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.order</code>.
	 */
	public Integer getOrder() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>media.playlist_entry.resource</code>.
	 */
	public void setResource(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.resource</code>.
	 */
	public String getResource() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, Integer, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, Integer, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, Integer, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PlaylistEntry.PLAYLIST_ENTRY.PLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PlaylistEntry.PLAYLIST_ENTRY.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return PlaylistEntry.PLAYLIST_ENTRY.ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PlaylistEntry.PLAYLIST_ENTRY.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPlaylist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getOrder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value1(String value) {
		setPlaylist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value2(String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value3(Integer value) {
		setOrder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value4(String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord values(String value1, String value2, Integer value3, String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaylistEntryRecord
	 */
	public PlaylistEntryRecord() {
		super(PlaylistEntry.PLAYLIST_ENTRY);
	}

	/**
	 * Create a detached, initialised PlaylistEntryRecord
	 */
	public PlaylistEntryRecord(String playlist, String user, Integer order, String resource) {
		super(PlaylistEntry.PLAYLIST_ENTRY);

		setValue(0, playlist);
		setValue(1, user);
		setValue(2, order);
		setValue(3, resource);
	}
}
