/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

import net.feminaexlux.player.model.tables.PlaylistEntry;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaylistEntryRecord extends TableRecordImpl<PlaylistEntryRecord> implements Record3<String, Integer, String> {

	private static final long serialVersionUID = 1014204279;

	/**
	 * Setter for <code>media.playlist_entry.playlist</code>.
	 */
	public void setPlaylist(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.playlist</code>.
	 */
	public String getPlaylist() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>media.playlist_entry.order</code>.
	 */
	public void setOrder(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.order</code>.
	 */
	public Integer getOrder() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>media.playlist_entry.resource</code>.
	 */
	public void setResource(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.resource</code>.
	 */
	public String getResource() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PlaylistEntry.PLAYLIST_ENTRY.PLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return PlaylistEntry.PLAYLIST_ENTRY.ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PlaylistEntry.PLAYLIST_ENTRY.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPlaylist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getOrder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value1(String value) {
		setPlaylist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value2(Integer value) {
		setOrder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value3(String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord values(String value1, Integer value2, String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaylistEntryRecord
	 */
	public PlaylistEntryRecord() {
		super(PlaylistEntry.PLAYLIST_ENTRY);
	}

	/**
	 * Create a detached, initialised PlaylistEntryRecord
	 */
	public PlaylistEntryRecord(String playlist, Integer order, String resource) {
		super(PlaylistEntry.PLAYLIST_ENTRY);

		setValue(0, playlist);
		setValue(1, order);
		setValue(2, resource);
	}
}
