/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlaylistEntryRecord extends org.jooq.impl.UpdatableRecordImpl<net.feminaexlux.player.model.tables.records.PlaylistEntryRecord> implements org.jooq.Record3<java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 2093999629;

	/**
	 * Setter for <code>media.playlist_entry.playlist</code>.
	 */
	public void setPlaylist(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.playlist</code>.
	 */
	public java.lang.String getPlaylist() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>media.playlist_entry.order</code>.
	 */
	public void setOrder(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.order</code>.
	 */
	public java.lang.Integer getOrder() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>media.playlist_entry.resource</code>.
	 */
	public void setResource(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.playlist_entry.resource</code>.
	 */
	public java.lang.String getResource() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY.PLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY.ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY.RESOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPlaylist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getOrder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getResource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value1(java.lang.String value) {
		setPlaylist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value2(java.lang.Integer value) {
		setOrder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord value3(java.lang.String value) {
		setResource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaylistEntryRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaylistEntryRecord
	 */
	public PlaylistEntryRecord() {
		super(net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY);
	}

	/**
	 * Create a detached, initialised PlaylistEntryRecord
	 */
	public PlaylistEntryRecord(java.lang.String playlist, java.lang.Integer order, java.lang.String resource) {
		super(net.feminaexlux.player.model.tables.PlaylistEntry.PLAYLIST_ENTRY);

		setValue(0, playlist);
		setValue(1, order);
		setValue(2, resource);
	}
}
