/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ResourceRecord extends org.jooq.impl.UpdatableRecordImpl<net.feminaexlux.player.model.tables.records.ResourceRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -2107345468;

	/**
	 * Setter for <code>media.resource.checksum</code>.
	 */
	public void setChecksum(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.resource.checksum</code>.
	 */
	public java.lang.String getChecksum() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>media.resource.directory</code>.
	 */
	public void setDirectory(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>media.resource.directory</code>.
	 */
	public java.lang.String getDirectory() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>media.resource.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>media.resource.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>media.resource.lastAccessed</code>.
	 */
	public void setLastaccessed(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>media.resource.lastAccessed</code>.
	 */
	public java.sql.Timestamp getLastaccessed() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.feminaexlux.player.model.tables.Resource.RESOURCE.CHECKSUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return net.feminaexlux.player.model.tables.Resource.RESOURCE.DIRECTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return net.feminaexlux.player.model.tables.Resource.RESOURCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return net.feminaexlux.player.model.tables.Resource.RESOURCE.LASTACCESSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getChecksum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDirectory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getLastaccessed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value1(java.lang.String value) {
		setChecksum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value2(java.lang.String value) {
		setDirectory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord value4(java.sql.Timestamp value) {
		setLastaccessed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ResourceRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ResourceRecord
	 */
	public ResourceRecord() {
		super(net.feminaexlux.player.model.tables.Resource.RESOURCE);
	}

	/**
	 * Create a detached, initialised ResourceRecord
	 */
	public ResourceRecord(java.lang.String checksum, java.lang.String directory, java.lang.String name, java.sql.Timestamp lastaccessed) {
		super(net.feminaexlux.player.model.tables.Resource.RESOURCE);

		setValue(0, checksum);
		setValue(1, directory);
		setValue(2, name);
		setValue(3, lastaccessed);
	}
}
