/**
 * This class is generated by jOOQ
 */
package net.feminaexlux.player.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.5.0"
		},
		comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TypeRecord extends org.jooq.impl.UpdatableRecordImpl<net.feminaexlux.player.model.tables.records.TypeRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = -1517243645;

	/**
	 * Setter for <code>media.type.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>media.type.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return net.feminaexlux.player.model.tables.Type.TYPE.TYPE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TypeRecord value1(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TypeRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TypeRecord
	 */
	public TypeRecord() {
		super(net.feminaexlux.player.model.tables.Type.TYPE);
	}

	/**
	 * Create a detached, initialised TypeRecord
	 */
	public TypeRecord(java.lang.String type) {
		super(net.feminaexlux.player.model.tables.Type.TYPE);

		setValue(0, type);
	}
}
